version: 2

sources:
   - name: raw
     schema: "{{ target.schema }}"
     loader: bigquery
     description: day 1 of dbt

     tables:
       - name: sales
         identifier : raw_gz_sales
       - name: product
         identifier : raw_gwz_product
       - name: ship
         identifier : raw_gz_ship