version: 2

sources:
   - name: gz_raw_data
     database: dynamic-sanctum-455919-n9
     schema: gz_raw_data
     loader: bigquery
     description: day 1 of dbt

     tables:
       - name: sales
         identifier : raw_gz_sales
       - name: product
         identifier : raw_gwz_product
       - name: ship
         identifier : raw_gz_ship